// Emit TanStack Query v5 hooks: GET -> useXQuery, mutating verbs -> useXMutation.

import { Contract, Endpoint, requestTypeName, responseTypeName } from '../contract';
import { camelCase, pascalCase } from '../naming';
import { baseTypeName } from '../contract';

export function emitHooks(contract: Contract): string {
  const usedTypes = new Set<string>();
  const blocks: string[] = [];
  let hasMutation = false;

  for (const ep of contract.endpoints) {
    if (ep.method === 'get') blocks.push(emitQuery(ep, usedTypes));
    else {
      hasMutation = true;
      blocks.push(emitMutation(ep, usedTypes));
    }
  }

  const rqImports = ['useQuery'];
  if (hasMutation) rqImports.push('useMutation', 'useQueryClient');
  const typeImports = usedTypes.size
    ? `import type { ${[...usedTypes].sort().join(', ')} } from './types';\n`
    : '';

  return (
    `// hooks.ts — generated by Typesmith from "${contract.title}"\n` +
    `import { ${rqImports.join(', ')} } from '@tanstack/react-query';\n` +
    typeImports +
    `\n` +
    `async function fetchJson<T>(url: string, init?: RequestInit): Promise<T> {\n` +
    `  const res = await fetch(url, init);\n` +
    `  if (!res.ok) throw new Error(res.status + ' ' + res.statusText);\n` +
    `  return res.status === 204 ? (undefined as T) : res.json();\n` +
    `}\n\n` +
    blocks.join('\n\n') +
    '\n'
  );
}

function urlExpr(ep: Endpoint): { expr: string; needsSearch: boolean } {
  const template = ep.path.replace(/\{(\w+)\}/g, (_, p) => '${' + camelCase(p) + '}');
  const needsBacktick = template.includes('${');
  const base = needsBacktick ? '`' + template + '`' : `'${ep.path}'`;
  return { expr: base, needsSearch: ep.queryParams.length > 0 };
}

function paramSig(ep: Endpoint): string[] {
  return ep.pathParams.map((p) => `${camelCase(p)}: string`);
}

function emitQuery(ep: Endpoint, usedTypes: Set<string>): string {
  const resp = ep.response ? responseTypeName(ep) : 'void';
  if (ep.response) usedTypes.add(resp);
  const hookName = 'use' + (baseTypeName(ep) || pascalCase(ep.name)) + 'Query';
  const args = [...paramSig(ep)];
  if (ep.queryParams.length) {
    const qFields = ep.queryParams
      .map((q) => `${camelCase(q.name)}${q.required ? '' : '?'}: string`)
      .join('; ');
    args.push(`params${ep.queryParams.every((q) => !q.required) ? '?' : ''}: { ${qFields} }`);
  }
  const keyParts = [`'${keyRoot(ep)}'`, ...ep.pathParams.map((p) => camelCase(p))];
  if (ep.queryParams.length) keyParts.push('params');
  const { expr } = urlExpr(ep);
  const urlLines = ep.queryParams.length
    ? `      const search = new URLSearchParams(Object.entries(params ?? {}).filter(([, v]) => v != null) as [string, string][]);\n` +
      `      const qs = search.size ? '?' + search.toString() : '';\n` +
      `      return fetchJson<${resp}>(${expr} + qs);\n`
    : `      return fetchJson<${resp}>(${expr});\n`;
  const comment = `/** ${ep.method.toUpperCase()} ${ep.path}${ep.summary ? ' — ' + ep.summary : ''} */`;
  return (
    `${comment}\n` +
    `export function ${hookName}(${args.join(', ')}) {\n` +
    `  return useQuery({\n` +
    `    queryKey: [${keyParts.join(', ')}],\n` +
    `    queryFn: () => {\n` +
    urlLines.replace(/^ {6}/gm, '      ') +
    `    },\n` +
    `  });\n` +
    `}`
  );
}

function emitMutation(ep: Endpoint, usedTypes: Set<string>): string {
  const resp = ep.response ? responseTypeName(ep) : 'void';
  if (ep.response) usedTypes.add(resp);
  const req = ep.requestBody ? requestTypeName(ep) : undefined;
  if (req) usedTypes.add(req);
  const hookName = 'use' + pascalCase(ep.name) + 'Mutation';

  const varFields: string[] = ep.pathParams.map((p) => `${camelCase(p)}: string`);
  if (req) varFields.push(`body: ${req}`);
  const varsType = varFields.length ? `{ ${varFields.join('; ')} }` : 'void';
  const destructure = varFields.length
    ? `({ ${[...ep.pathParams.map((p) => camelCase(p)), ...(req ? ['body'] : [])].join(', ')} }: ${varsType})`
    : `(_: ${varsType})`;

  const { expr } = urlExpr(ep);
  const init =
    `{\n        method: '${ep.method.toUpperCase()}',\n` +
    (req ? `        headers: { 'Content-Type': 'application/json' },\n        body: JSON.stringify(body),\n` : '') +
    `      }`;
  const comment = `/** ${ep.method.toUpperCase()} ${ep.path}${ep.summary ? ' — ' + ep.summary : ''} */`;
  return (
    `${comment}\n` +
    `export function ${hookName}() {\n` +
    `  const queryClient = useQueryClient();\n` +
    `  return useMutation({\n` +
    `    mutationFn: ${destructure} =>\n` +
    `      fetchJson<${resp}>(${expr}, ${init}),\n` +
    `    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['${keyRoot(ep)}'] }),\n` +
    `  });\n` +
    `}`
  );
}

function keyRoot(ep: Endpoint): string {
  const seg = ep.path.split('/').filter((s) => s && !s.startsWith('{') && s !== 'api')[0] ?? ep.name;
  return camelCase(seg) || camelCase(ep.name);
}
