// Emit deterministic mock fixtures + MSW handlers wired to every endpoint.

import { Contract, responseTypeName } from '../contract';
import { pascalCase } from '../naming';
import { mockResponse } from '../mock';

export function emitMocks(contract: Contract): string {
  const fixtures: string[] = [];
  const handlers: string[] = [];
  const usedTypes = new Set<string>();

  for (const ep of contract.endpoints) {
    const mswPath = ep.path.replace(/\{(\w+)\}/g, ':$1');
    if (ep.response) {
      const constName = 'mock' + pascalCase(ep.name) + 'Response';
      const typeName = responseTypeName(ep);
      usedTypes.add(typeName);
      const data = mockResponse(ep.response, ep.name);
      fixtures.push(
        `/** ${ep.method.toUpperCase()} ${ep.path} */\n` +
          `export const ${constName}: ${typeName} = ${JSON.stringify(data, null, 2)};`
      );
      const status = ep.method === 'post' ? ', { status: 201 }' : '';
      handlers.push(`  http.${ep.method}('${mswPath}', () => HttpResponse.json(${constName}${status})),`);
    } else {
      handlers.push(`  http.${ep.method}('${mswPath}', () => new HttpResponse(null, { status: 204 })),`);
    }
  }

  const typeImports = usedTypes.size
    ? `import type { ${[...usedTypes].sort().join(', ')} } from './types';\n`
    : '';

  return (
    `// mocks.ts — generated by Typesmith from "${contract.title}"\n` +
    `// Fixtures are deterministic (seeded PRNG) so snapshots stay stable.\n` +
    `import { http, HttpResponse } from 'msw';\n` +
    typeImports +
    '\n' +
    fixtures.join('\n\n') +
    '\n\n' +
    `export const handlers = [\n${handlers.join('\n')}\n];\n` +
    '\n' +
    `// setup (browser): import { setupWorker } from 'msw/browser';\n` +
    `// export const worker = setupWorker(...handlers);\n`
  );
}
