// Emit TypeScript interfaces + per-endpoint request/response aliases.

import { Field, Shape, splitNullable } from '../infer';
import { Contract, requestTypeName, responseTypeName } from '../contract';
import { propKey, typeNameFrom } from '../naming';
import { NameRegistry } from './registry';

export function emitTypescript(contract: Contract): string {
  const reg = new NameRegistry();
  const decls: string[] = [];

  const ref = (shape: Shape, hint: string): string => {
    const { inner, nullable } = splitNullable(shape);
    const t = refInner(inner, hint);
    return nullable ? `${t} | null` : t;
  };

  const refInner = (shape: Shape, hint: string): string => {
    switch (shape.kind) {
      case 'object': {
        const { name, isNew } = reg.claim(shape, hint);
        if (isNew) declareInterface(name, shape.fields);
        else declareByName(name);
        return name;
      }
      case 'array': {
        const item = ref(shape.items, typeNameFrom(hint));
        return needsParens(item) ? `(${item})[]` : `${item}[]`;
      }
      case 'primitive':
        return shape.type;
      case 'literal':
        return JSON.stringify(shape.value);
      case 'null':
        return 'null';
      case 'unknown':
        return 'unknown';
      case 'union':
        return shape.variants.map((v) => refInner(v, hint)).join(' | ');
    }
  };

  const declareInterface = (name: string, fields: Field[]) => {
    const lines = fields.map((f) => {
      const t = ref(f.shape, typeNameFrom(f.name));
      const fmt = formatComment(f.shape);
      return `  ${propKey(f.name)}${f.optional ? '?' : ''}: ${t};${fmt}`;
    });
    decls.push(`export interface ${name} {\n${lines.join('\n')}\n}`);
  };

  // Seed component schemas in two passes so every given name is claimed
  // before any body is walked — otherwise a nested reference to a later
  // component (e.g. Todo.assignee → User) would rename it after its field.
  const pending = new Map<string, Field[]>();
  const declared = new Set<string>();
  const declareByName = (name: string) => {
    const fields = pending.get(name);
    if (!fields || declared.has(name)) return;
    declared.add(name);
    declareInterface(name, fields);
  };
  for (const named of contract.namedShapes) {
    if (named.shape.kind === 'object') {
      const { name, isNew } = reg.claim(named.shape, named.name);
      if (isNew) pending.set(name, named.shape.fields);
    }
  }
  for (const name of pending.keys()) declareByName(name);

  const aliases: string[] = [];
  for (const ep of contract.endpoints) {
    const header = `/** ${ep.method.toUpperCase()} ${ep.path}${ep.summary ? ' — ' + ep.summary : ''} */`;
    if (ep.requestBody) {
      const t = ref(ep.requestBody, requestTypeName(ep));
      if (t !== requestTypeName(ep)) aliases.push(`${header}\nexport type ${requestTypeName(ep)} = ${t};`);
      else aliases.push(header.replace(' */', ' → ' + t + ' */'));
    }
    if (ep.response) {
      const t = ref(ep.response, responseTypeName(ep));
      if (t !== responseTypeName(ep)) aliases.push(`${header}\nexport type ${responseTypeName(ep)} = ${t};`);
      else aliases.push(header.replace(' */', ' → ' + t + ' */'));
    }
  }

  const out = [`// types.ts — generated by Typesmith from "${contract.title}"`, '', ...decls, '', ...aliases];
  return out.join('\n\n').replace(/\n{3,}/g, '\n\n').trim() + '\n';
}

function needsParens(t: string): boolean {
  return t.includes('|') || t.includes('&');
}

function formatComment(shape: Shape): string {
  const { inner } = splitNullable(shape);
  if (inner.kind === 'primitive' && inner.format) return ` // ${inner.format}`;
  return '';
}
