// Emit Zod schemas mirroring the TypeScript types, plus z.infer aliases.

import { Field, Shape, splitNullable } from '../infer';
import { Contract, requestTypeName, responseTypeName } from '../contract';
import { propKey, typeNameFrom } from '../naming';
import { NameRegistry } from './registry';

export function emitZod(contract: Contract): string {
  const reg = new NameRegistry();
  const decls: string[] = [];

  const ref = (shape: Shape, hint: string): string => {
    const { inner, nullable } = splitNullable(shape);
    const z = refInner(inner, hint);
    return nullable ? `${z}.nullable()` : z;
  };

  const refInner = (shape: Shape, hint: string): string => {
    switch (shape.kind) {
      case 'object': {
        const { name, isNew } = reg.claim(shape, hint);
        if (isNew) declareSchema(name, shape.fields);
        else declareByName(name);
        return name + 'Schema';
      }
      case 'array':
        return `z.array(${ref(shape.items, typeNameFrom(hint))})`;
      case 'primitive': {
        if (shape.type === 'string') {
          switch (shape.format) {
            case 'uuid': return 'z.string().uuid()';
            case 'email': return 'z.string().email()';
            case 'url': return 'z.string().url()';
            case 'date-time': return 'z.string().datetime()';
            case 'date': return 'z.string().date()';
            default: return 'z.string()';
          }
        }
        return shape.type === 'number' ? 'z.number()' : 'z.boolean()';
      }
      case 'literal':
        return `z.literal(${JSON.stringify(shape.value)})`;
      case 'null':
        return 'z.null()';
      case 'unknown':
        return 'z.unknown()';
      case 'union': {
        const lits = shape.variants.filter((v) => v.kind === 'literal');
        if (lits.length === shape.variants.length && lits.every((l) => l.kind === 'literal' && typeof l.value === 'string')) {
          const values = lits.map((l) => JSON.stringify((l as { value: string }).value)).join(', ');
          return `z.enum([${values}])`;
        }
        return `z.union([${shape.variants.map((v) => refInner(v, hint)).join(', ')}])`;
      }
    }
  };

  const declareSchema = (name: string, fields: Field[]) => {
    const lines = fields.map((f) => {
      const z = ref(f.shape, typeNameFrom(f.name));
      return `  ${propKey(f.name)}: ${z}${f.optional ? '.optional()' : ''},`;
    });
    decls.push(
      `export const ${name}Schema = z.object({\n${lines.join('\n')}\n});\n` +
        `export type ${name} = z.infer<typeof ${name}Schema>;`
    );
  };

  // Claim all component names before walking any body (see typescript.ts);
  // declareByName recursion also puts dependency schemas above their users,
  // which zod consts require.
  const pending = new Map<string, Field[]>();
  const declared = new Set<string>();
  const declareByName = (name: string) => {
    const fields = pending.get(name);
    if (!fields || declared.has(name)) return;
    declared.add(name);
    declareSchema(name, fields);
  };
  for (const named of contract.namedShapes) {
    if (named.shape.kind === 'object') {
      const { name, isNew } = reg.claim(named.shape, named.name);
      if (isNew) pending.set(name, named.shape.fields);
    }
  }
  for (const name of pending.keys()) declareByName(name);

  const aliases: string[] = [];
  for (const ep of contract.endpoints) {
    const header = `/** ${ep.method.toUpperCase()} ${ep.path} */`;
    if (ep.requestBody) {
      const z = ref(ep.requestBody, requestTypeName(ep));
      if (z !== requestTypeName(ep) + 'Schema') {
        aliases.push(`${header}\nexport const ${requestTypeName(ep)}Schema = ${z};`);
      }
    }
    if (ep.response) {
      const z = ref(ep.response, responseTypeName(ep));
      if (z !== responseTypeName(ep) + 'Schema') {
        aliases.push(`${header}\nexport const ${responseTypeName(ep)}Schema = ${z};`);
      }
    }
  }

  const out = [
    `// schemas.ts — generated by Typesmith from "${contract.title}"`,
    `import { z } from 'zod';`,
    '',
    ...decls,
    '',
    ...aliases,
  ];
  return out.join('\n\n').replace(/\n{3,}/g, '\n\n').trim() + '\n';
}
